SET PATH=D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\CODE\Blog\Node\;D:\CODE\Blog\Git\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Users\extre\AppData\Local\Microsoft\WindowsApps;;D:\CODE\VScode\Microsoft VS Code\bin;C:\Users\extre\AppData\Roaming\npm;D:\CODE\Pycharm\PyCharm Community Edition 2023.2\bin;
SET CPU_TYPE=STM32F401CCUx
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=F401_ALL
SET CPU_CLOCK=0x017D7840
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmAsm" --Via "f401_freertosdemo\startup_stm32f401xc._ia"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\main.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\gpio.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\freertos.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\usart.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_it.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_msp.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_timebase_tim.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\delay.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_rcc.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_rcc_ex.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_flash.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_flash_ex.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_flash_ramfunc.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_gpio.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_dma_ex.__i"
"D:\WORK\SOFTWARES\MDK5\ARM\ARMCC\Bin\ArmCC" --Via "f401_freertosdemo\stm32f4xx_hal_dma.__i"
